import { GeminiProvider } from '../llm/gemini'

const CLASSIFIER_PROMPT = `You are a content safety classifier. The text below was generated by an AI character named Dadi, who is a warm Indian grandmother telling a fable to a child between 4 and 9 years old.

Your job is to determine if the text stays within the safe topical scope.

Safe topics: Indian folklore, the current story and its characters, Indian culture and traditions, food, animals, geography, plants, basic morals, the child's feelings about the story, simple age-appropriate history, small bits of Dadi's own remembered life (her village, her own grandmother, monsoon, gramophone, cardamom in chai).

Unsafe topics: violence beyond what is plainly in the story, anything sexual, drugs, contemporary politics, doctrinal religion or religious instruction, current events, real adult people not in the fable, anything that asks the child for personal information, anything frightening or distressing, URLs, emails, phone numbers, anything that suggests the child do something dangerous.

Return strict JSON: { "in_scope": boolean, "reason": string }

Text to classify:
`

export async function classifyOutput(
  text: string,
  apiKey: string,
): Promise<{ inScope: boolean; reason: string }> {
  try {
    const provider = new GeminiProvider(apiKey)
    const raw = await provider.generate(CLASSIFIER_PROMPT + text, 'You are a safety classifier. Return only JSON.')

    const jsonMatch = raw.match(/\{[\s\S]*\}/)
    if (!jsonMatch) return { inScope: true, reason: 'Could not parse classifier response' }

    const parsed = JSON.parse(jsonMatch[0]) as { in_scope: boolean; reason: string }
    return { inScope: parsed.in_scope, reason: parsed.reason }
  } catch {
    return { inScope: true, reason: 'Classifier error — defaulting to safe' }
  }
}
